import React from 'react'
import styles from "./page.module.css"

function sspage() {
  return (
    <div><p className={styles.p}>Neymar</p>
    <p>(born 5 February 1992), known as Neymar Júnior or mononymously as Neymar, is a Brazilian professional footballer who plays as a forward for Saudi Pro League club Al Hilal and the Brazil national team. A technically gifted player, Neymar is a prolific goalscorer and playmaker renowned for his flamboyant style of play, passing abilities and two-footedness. He finished third for the FIFA Ballon d'Or in 2015 and 2017 and is a recipient of the FIFA Puskás Award. Neymar has scored at least 100 goals for three different clubs, making him one of the few players to achieve this feat.[3]

Neymar came into prominence at Santos, where he made his professional debut aged 17. Soon becoming the Brazilian league's star player, he won the 2011 Copa Libertadores with Santos, being their first since 1963. He was named the South American Footballer of the Year in 2011 and 2012, and relocated to Europe to join Barcelona in 2013. In his second season, as part of Barcelona's attacking trio with Lionel Messi and Luis Suárez, dubbed MSN, he won the continental treble of La Liga, the Copa del Rey, and the UEFA Champions League; he was the tied top scorer of the Champions League campaign, as well as the top scorer in the Copa del Rey.

Motivated to be the focal player at club level, Neymar joined Paris Saint-Germain (PSG) in 2017[4] in a €222 million transfer, which made him the most expensive player ever.[note 1] In his debut season, Neymar was voted Ligue 1 Player of the Year and won his first Ligue 1 title, which he would go on to win four more times. He continued to excel in French football in his second season, and in the following season was integral to PSG reaching its first ever Champions League final. In 2020-21, he cemented himself as the highest scoring Brazilian player in Champions League history.[7] Reoccurring injuries riddled Neymar's playing time; in 2023 he left PSG as one of their top goalscorers of all time, signing for Al Hilal in a lucrative deal.

Debuting for Brazil aged 18, Neymar is the all-time top goalscorer for his national team with 79 goals in 128 matches. He won the 2013 FIFA Confederations Cup, winning the Golden Ball. In his first FIFA World Cup, the 2014 edition, he was named in the Dream Team. His participation in the 2015 Copa América was cut short by a suspension, before captaining Brazil to their first Olympic gold medal in men's football at the 2016 Summer Olympics, having already achieving a silver medal at the 2012 edition. Having renounced the captaincy, he featured at the 2018 World Cup, and after missing the 2019 Copa América through injury, helped Brazil to a runner-up finish at the 2021 tournament, in which he won the joint Best Player award alongside Messi. At the 2022 World Cup, he joined Pelé and Ronaldo as the only Brazilians to score in three World Cups. Neymar has won a record six Samba Gold awards, given to the best Brazilian player in Europe.

Neymar has been named in the FIFA FIFPro World11 and the UEFA Team of the Year twice, and the UEFA Champions League Squad of the Season three times. Off the pitch, he ranks among the world's most prominent sportsmen. SportsPro named him the most marketable athlete in the world in 2012 and 2013, and ESPN cited him as the world's fourth-most-famous athlete in 2016. In 2017, Time included him in its annual list of the 100 most influential people in the world.[8] In 2018, France Football ranked Neymar the world's third-highest-paid footballer. The following year, Forbes ranked him the world's third-highest-paid athlete,[9] dropping a spot to fourth in 2020.[10]</p></div>
  )
}

export default sspage